# Generated by Django 4.0.4 on 2022-05-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='uel',
            new_name='url',
        ),
    ]
